const paragraphs = [
  "The first rays of sunlight painted the sky with beautiful shades of orange and gold as the quiet town slowly came to life. People opened their shops, children prepared for school, and birds filled the air with cheerful songs. A gentle breeze carried the refreshing scent of flowers across the streets. Every new morning offered another opportunity to learn, improve, and chase dreams with confidence. Even the smallest positive action could create a meaningful difference, reminding everyone that every day was a fresh beginning filled with endless possibilities and hope.",

  "Modern technology has changed the world in remarkable ways, making communication faster and learning more accessible than ever before. Students can discover valuable information within seconds, connect with experts across the globe, and create amazing projects using simple programming skills. Innovation continues to inspire creative thinkers who solve real-world problems through determination and imagination. While technology offers countless advantages, it should always be used responsibly and wisely. Balancing digital life with meaningful human interaction helps people build stronger relationships, healthier habits, and a brighter future for generations to come.",

  "A peaceful forest is one of nature's greatest treasures, filled with towering trees, colorful flowers, flowing rivers, and countless fascinating animals. Every living creature plays an important role in maintaining the balance of the ecosystem. Birds spread seeds, insects pollinate flowers, and trees produce the oxygen that humans and animals depend upon every day. Protecting forests by planting trees, reducing pollution, and preventing unnecessary deforestation is everyone's responsibility. Small environmental actions performed consistently can protect wildlife, preserve biodiversity, and ensure a healthier planet for future generations to enjoy.",

  "Reading books is one of the most rewarding habits anyone can develop because it expands knowledge, strengthens imagination, and improves communication skills. Every story introduces readers to new characters, exciting adventures, and valuable life lessons that remain unforgettable for years. Books encourage critical thinking, increase vocabulary, and improve concentration through consistent practice. Whether someone enjoys fiction, science, history, or biographies, reading regularly opens countless doors to creativity and personal growth. A single inspiring book has the power to completely transform perspectives, motivate positive change, and build lifelong curiosity.",

  "Sports teach valuable lessons that extend far beyond the playing field by encouraging teamwork, discipline, patience, and determination. Every practice session develops stronger skills, greater confidence, and a healthier lifestyle. Winning a competition brings excitement, while losing teaches resilience and the importance of continuous improvement. Athletes learn to respect coaches, teammates, opponents, and the rules that make every game fair. Regular physical activity improves both mental and physical health, helping people stay energetic, focused, and motivated while developing lifelong friendships through shared experiences and unforgettable achievements.",

  "Traveling allows people to experience different cultures, traditions, languages, and breathtaking landscapes while creating unforgettable memories. Visiting historical monuments, tasting local cuisine, and meeting friendly people broaden perspectives and deepen appreciation for the diversity of our world. Every destination offers unique lessons about history, architecture, customs, and daily life. Exploring unfamiliar places encourages adaptability, confidence, and curiosity while inspiring travelers to value both similarities and differences among cultures. Every journey becomes a collection of meaningful experiences that remain cherished throughout life and inspire future adventures with excitement.",

  "A successful project begins with a clear goal, careful planning, and consistent effort from beginning to completion. Breaking large tasks into smaller manageable steps makes difficult challenges easier to overcome. Teamwork encourages creative thinking because different people contribute unique ideas and perspectives. Regular testing, reviewing feedback, and making improvements help produce better results before the final presentation. Mistakes should never discourage progress because every challenge provides an opportunity to learn something valuable. Persistence, patience, and dedication remain the key ingredients behind every successful achievement and long-term accomplishment.",

  "Healthy habits form the foundation of a happy and productive life by supporting both physical and mental well-being every single day. Eating balanced meals, drinking enough water, exercising regularly, and sleeping sufficiently provide the energy needed for daily activities. Managing stress through relaxation, positive thinking, and meaningful hobbies improves emotional health and strengthens confidence. Avoiding harmful habits while maintaining self-discipline leads to long-term benefits. Small healthy decisions repeated consistently over time create remarkable improvements that positively influence every aspect of life, happiness, and overall success.",

  "The night sky has fascinated humanity for thousands of years with its sparkling stars, mysterious planets, and endless galaxies waiting to be explored. Scientists use advanced telescopes and powerful spacecraft to uncover the secrets of the universe while expanding our understanding of space. Every new discovery answers important questions while creating exciting mysteries for future generations to investigate. Space exploration has also contributed to countless technological innovations that improve everyday life on Earth. Curiosity, imagination, and scientific research continue inspiring people to dream beyond the limits of our planet.",

  "Success is rarely achieved overnight because meaningful accomplishments require patience, consistent effort, continuous learning, and unwavering determination. Every successful person has faced obstacles, failures, and moments of self-doubt before reaching their goals. Instead of giving up, they viewed every mistake as an opportunity to improve and become stronger. Maintaining a positive mindset, setting realistic goals, and working diligently every day gradually builds confidence and experience. Every small step forward, no matter how insignificant it may seem, contributes to a brighter future filled with achievement, personal growth, and lasting satisfaction."
  
];